### ISSUE TITLE
How to merge adult and pediatric data into data_loader_3d_balanced

### ISSUE THREAD

**Issue by Echoha** [Fjr9516/DA_nnUNet#1]
Hello,

Your work is fantastic and highly innovative. However, I am having trouble understanding how to merge two preprocessed datasets and run nnUNetv2_train 237 3d_fullres_bs4 0 -tr nnUNetTrainerDA_500ep_noDS_4Convs --npz. My BraTS2023_PED dataset's data_id is 237, and I need to merge adult and pediatric data into data_loader_3d_balanced. I encounter an error:
     data_loader_3d_balanced.py", line 34, in get_indices *np.random.choice(class_indices, int(self.batch_size / len(self.indices)), replace=True,File "numpy/random/mtrand.pyx", line 951, in numpy.random.mtrand.RandomState.choice ValueError: 'a' cannot be empty unless no samples are taken.

Could you please guide me on how to resolve this issue?

Thank you!

**Comment by Fjr9516** [comment]
Hi,

To proceed, please place both datasets into a single nnUNet preprocessed folder. Additionally, adjust the domain_mapping to align with your data. Refer to:
[Link to the code](https://github.com/Fjr9516/DA_nnUNet/blob/d783a2440095e91555c6f6e87b5361614e616f8f/nnunetv2/training/nnUNetTrainer/customized/nnUNetTrainer_DANN.py#L85).
